# Generated by Django 3.2.25 on 2025-09-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame_size',
        ),
    ]
